[alembic]
script_location = alembic
sqlalchemy.url = sqlite:///./.serah/serah.sqlite
prepend_sys_path = src
path_separator = os

[loggers]
keys = root
handlers =
level = WARN

[handlers]

[formatters]

[logger_root]
level = WARN
handlers =
